name: ATPipi
version: 1.1
main: com.example.atpipi.ATPipiPlugin
api-version: 1.13  # Минимальная версия API (можно указать 1.12, но без api-version)
softdepend:
  - No  # Если вы хотите, чтобы плагин зависел от сторонних плагинов (например, Vault)
commands:
  atpipi:
    description: Пускать желтые блоки бетона из ног игрока.
    usage: /atpipi
    permission: atpipi.use

permissions:
  atpipi.use:
    description: Разрешение на использование команды /atpipi
    default: true
